name: FactLine_Auto_Update

on:
  schedule:
    - cron: '0 21 * * *'
    - cron: '0 9 * * *'
  workflow_dispatch:

# 警告に対応するための環境変数を追加
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 現時点で最新

      - name: Set up Python
        uses: actions/setup-python@v5 # 現時点で最新
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install feedparser requests yfinance

      - name: Run scripts
        env:
          WEBAPP_URL: ${{ secrets.WEBAPP_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python main.py
