name: FactLine_Auto_Update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Post Test Data
        env:
          MY_URL: ${{ secrets.WEBAPP_URL }}
        run: |
          curl -L -X POST "$MY_URL" \
          -H "Content-Type: application/json" \
          -d '{"title_en":"Test","summary_jp":"成功です","trust_level":"High","impact":"Low","link":"https://ex.com"}'
